# Generated by Django 4.2.11 on 2026-04-23 22:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detallemovimiento_id_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreTurno',
            fields=[
                ('id_cierre_turno', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('CERRADO', 'Cerrado')], default='EN_PROCESO', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('mostrador_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('raciones_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ajuste_por_error_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pan_especial_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('detalle_pan_especial', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('quintales_cocidos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilos_directos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidades_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilos_equivalentes', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('kilos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rinde', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_jornada', models.ForeignKey(db_column='id_jornada', on_delete=django.db.models.deletion.CASCADE, to='api.jornadadiaria')),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'db_table': 'cierre_turno',
                'indexes': [models.Index(fields=['id_jornada'], name='idx_ct_jornada'), models.Index(fields=['id_turno'], name='idx_ct_turno'), models.Index(fields=['estado'], name='idx_ct_estado')],
            },
        ),
        migrations.AddConstraint(
            model_name='cierreturno',
            constraint=models.UniqueConstraint(fields=('id_jornada', 'id_turno'), name='unique_cierre_turno_jornada_turno'),
        ),
        migrations.AddConstraint(
            model_name='cierreturno',
            constraint=models.CheckConstraint(check=models.Q(('estado__in', ['EN_PROCESO', 'CERRADO'])), name='check_cierre_turno_estado'),
        ),
        migrations.AddConstraint(
            model_name='cierreturno',
            constraint=models.CheckConstraint(check=models.Q(('ajuste_por_error_kg', 0), models.Q(('observacion__isnull', False), models.Q(('observacion', ''), _negated=True)), _connector='OR'), name='check_cierre_turno_ajuste_observacion'),
        ),
    ]
